spring:
  application:
    name: products-service
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
management:
  endpoints:
    web.exposure.include: health,info,metrics
  endpoint.health.probes.enabled: true

---
spring:
  config.activate.on-profile: local
  datasource:
    url: jdbc:postgresql://localhost:5432/products
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
server.port: 8080

---
spring:
  config.activate.on-profile: k8s
  datasource:
    url: jdbc:postgresql://${DB_HOST:postgres}:5432/${DB_NAME:products}
    username: ${DB_USER}
    password: ${DB_PASS}
