apiVersion: apps/v1
kind: Deployment
metadata: { name: products-api }
spec:
  replicas: 1
  selector: { matchLabels: { app: products-api } }
  template:
    metadata: { labels: { app: products-api } }
    spec:
      containers:
        - name: api
          image: products-api:local
          imagePullPolicy: Never
          ports: [{ containerPort: 8080 }]
          env:
            - name: SPRING_PROFILES_ACTIVE
              valueFrom: { configMapKeyRef: { name: app-config, key: SPRING_PROFILES_ACTIVE } }
            - name: DB_HOST
              valueFrom: { configMapKeyRef: { name: app-config, key: DB_HOST } }
            - name: DB_NAME
              valueFrom: { configMapKeyRef: { name: app-config, key: DB_NAME } }
            - name: DB_USER
              valueFrom: { secretKeyRef: { name: app-secret, key: db-user } }
            - name: DB_PASS
              valueFrom: { secretKeyRef: { name: app-secret, key: db-pass } }
