apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: products-api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: products-api
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 35   # alvo baixo para escalar rápido
  behavior:                        # acelera scale-up e evita "yo-yo" no down
    scaleUp:
      stabilizationWindowSeconds: 15
      policies:
        - type: Percent
          value: 100              # pode dobrar a cada 60s
          periodSeconds: 60
    scaleDown:
      stabilizationWindowSeconds: 120
      policies:
        - type: Percent
          value: 100
          periodSeconds: 60
