apiVersion: apps/v1
kind: Deployment
metadata: { name: postgres }
spec:
  replicas: 1
  selector: { matchLabels: { app: postgres } }
  template:
    metadata: { labels: { app: postgres } }
    spec:
      containers:
        - name: postgres
          image: postgres:16
          env:
            - name: POSTGRES_DB
              value: products
            - name: POSTGRES_USER
              valueFrom: { secretKeyRef: { name: app-secret, key: db-user } }
            - name: POSTGRES_PASSWORD
              valueFrom: { secretKeyRef: { name: app-secret, key: db-pass } }
          volumeMounts:
            - name: pgdata
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: pgdata
          persistentVolumeClaim: { claimName: pgdata-pvc }
